### ISSUE TITLE
Error when opening in split pane

### ISSUE THREAD

**Issue by sundarvisweswaran** [unigraph-dev/unigraph-dev#234]
After updating in the settings to open components in a new pane instead of the tab, clicking on any component, results in the error.

<img width="1225" alt="Screen Shot 2021-11-22 at 3 45 48 PM" src="https://user-images.githubusercontent.com/3332832/142932983-b0638143-ffa7-4041-bb43-9b44f3700696.png">

**Comment by thesophiaxu** [comment]
Hi! This problem should've been fixed in an earlier release - forgot to close this until now. The current version can open tabs in split pane just fine.
