### ISSUE TITLE
`Enter` should add a to-do when using the `ADD` text input in the To-Dos view

### ISSUE THREAD

**Issue by asampal** [unigraph-dev/unigraph-dev#278]
When hitting `Enter`, I would expect that the currently typed text is added to the list of tasks, when using the `ADD` text input box:

![image](https://user-images.githubusercontent.com/281639/147034521-7b279a1c-a9ba-40de-bb8a-770412133e47.png)
  

Windows 11, Unigraph 16d448f

**Comment by thesophiaxu** [comment]
This UI will be updated to use the global omnibar - currently we've removed the add button, but there will be a floating action button in the future that takes you to the omnibar.
