### ISSUE TITLE
After adding a task using the `ADD` button on the To-Dos view, the text input box should be cleared and focused

### ISSUE THREAD

**Issue by asampal** [unigraph-dev/unigraph-dev#279]
I would expect that the text input box is cleared and focused after an item is entered using the `ADD` button, so that a new item can rapidly be entered. As is, the previously entered text remains there and must be cleared.

Windows 11, Unigraph 16d448f

**Comment by thesophiaxu** [comment]
The text input box has been replaced with add button which comes with this feature
