### ISSUE TITLE
Notes should not require every line of content to be bulleted

### ISSUE THREAD

**Issue by asampal** [unigraph-dev/unigraph-dev#281]
Currently, every line of content in a note has a leading bullet marker. This is quite a heavy marker visually and should be optional.

Windows 11, Unigraph 16d448f

**Comment by asampal** [comment]
How do you make a line of content non-bulleted?

**Comment by thesophiaxu** [comment]
You can set all children of a block to be bulleted/not bulleted by right
clicking on the block or use the top-right drop down menu (for root
blocks).

For visual consistency, this setting is applied to all children for now.
