### ISSUE TITLE
External links can't be followed

### ISSUE THREAD

**Issue by asampal** [unigraph-dev/unigraph-dev#283]
External links are properly rendered in content, but it doesn't seem possible to follow them. In a note, a single click on a link just expands text to show the link markup. In a ToDo, a single click does nothing. In either case, a `ctrl + click` or other key/mouse combination also doesn't follow the link to display it, e.g., in a browser/Unigraph view, etc.

Windows 11, Unigraph 16d448f

**Comment by thesophiaxu** [comment]
Hi! this has been fixed in the latest commit.
