### ISSUE TITLE
After creating a new note, `Click here to start writing` should be selected and focused

### ISSUE THREAD

**Issue by asampal** [unigraph-dev/unigraph-dev#285]
`Click here to start writing` should be selected and focused so that one can just start typing note content.

Windows 11, Unigraph 16d448f

**Comment by asampal** [comment]
Again, I might not have updated the needed packages (did `notes, core, home`), but not seeing this fix. What did I miss? 

It would be good if you could list packages that need refreshing when closing an issue, since it's not necessarily obvious to people not very familiar with the project or who haven't taken a close look at where the changes were made.

**Comment by thesophiaxu** [comment]
Related to focus state refactor

**Comment by asampal** [comment]
It's not clear if this is supposed to be fixed in latest (it's still an issue in Windows).

**Comment by thesophiaxu** [comment]
This has been fixed in the latest version (2 days ago): we're now using a separate set of client state (isomorphic at the api level) and sync it with the server state. Also the editor should be much faster now!
