### ISSUE TITLE
There should be a way to refresh (or at least notify of) updated packages

### ISSUE THREAD

**Issue by asampal** [unigraph-dev/unigraph-dev#297]
When commits are made to Unigraph it's not necessarily obvious, to developers who are trying to stay up to date with the latest, which packages might need to be updated in Dgraph as a result of the changes.

It's not clear what approach would help the developer workflow wrt changed packages, but a few suggestions would be:

- Mention affected packages in commit messages so that devs could update as required in the Packages view.
- Provide a button in the Packages view to update all packages in a directory. In this way, devs unfamiliar with the complete codebase could just use that to update all of the standard packages in one shot.
- Since packages are versioned, a version comparison should be done for standard packages wrt the Dgraph version (of course this would assume a bump in the source version when any changes are made) when using the Packages view. A button should allow changed packages to be updated in Dgraph.

**Comment by asampal** [comment]
As possibly a quicker way to address this for the dev workflow, an npm script could do what I suggested as the second point, i.e. force update all packages in the standard directory.

**Comment by thesophiaxu** [comment]
This is actually one of the harder things to do, and is linked to the distribution flow (which we're still brainstorming how). I'll keep you posted for updates, but for now, just delete the database and initialize again every time you pull (unless you want to use it daily too)
