### ISSUE TITLE
Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style

### ISSUE THREAD

**Issue by asampal** [unigraph-dev/unigraph-dev#306]
Getting that error for a whole bunch of files when doing `yarn explorer-start`. Might want to not enforce the linebreak style.

![image](https://user-images.githubusercontent.com/281639/147629365-b9e581e5-a580-406a-9d3b-02e852dca9a1.png)

Windows 11, Unigraph 8eff74b4

**Comment by thesophiaxu** [comment]
yeah probably, since git I think use different line breaks depending on the platform

**Comment by thesophiaxu** [comment]
This should be fixed with the new version - just do a pull and run `yarn && yarn build-deps` and it should be good!
