### ISSUE TITLE
bug(notes): numbered lists are broken

### ISSUE THREAD

**Issue by TheExGenesis** [unigraph-dev/unigraph-dev#340]
It's probably a styling problem.

**Comment by dragonman225** [comment]
https://github.com/unigraph-dev/unigraph-dev/blob/d6566b0443782b9c091ff29372af8bf16f7b7432/packages/unigraph-dev-explorer/src/examples/semantic/Markdown.tsx#L183-L188

@TheExGenesis  The number list component is generated by the `compFactory` function, which adds `display: contents` to the rendered element, changing the default rendering behavior of the browser. I'm not sure why it's necessary. By contrast, the bullet list is not added `display: contents`, so it's rendered normally.
